In [4]:
import numpy as np
import scipy as sp
import pandas as pd
import os
import csv
years = ["2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023"]
for year in years:
    path = f"C:/Users/asobc/Harris-Public-Policy Dropbox/Alex Sobczynski/WorldBank_AFG_Climate/data/GLDAS_Processed/gldas_processed_{year}"
    path_big = f"C:/Users/asobc/Harris-Public-Policy Dropbox/Alex Sobczynski/WorldBank_AFG_Climate/data/GLDAS/csv_{year}/"
    files = os.listdir(path_big)
    csv_files = [file for file in files if file.endswith('.csv')]
    if csv_files:
        # Get the first CSV file
        first_csv_file = csv_files[0]
        print(first_csv_file)
        # Load the first CSV file into a pandas DataFrame
        data = pd.read_csv(os.path.join(path_big, first_csv_file), encoding='latin-1')

        # Display the loaded data
        print(data.columns)
    else:
        print("No CSV files found in the folder.")

    columns_to_extract = ['Unnamed: 0', 'lon', 'lat'] + [col for col in data.columns if col.startswith('TWS')]
    df_combined = data[columns_to_extract]
    print(df_combined.head(2))

    for file_name in os.listdir(path_big):
        if file_name.endswith('.csv') and file_name != first_csv_file:
            file_path = os.path.join(path_big, file_name)
            df = pd.read_csv(file_path)

            # Extract the columns that start with 'TWS' or 'GWS'
            columns_to_bind = [col for col in df.columns if col.startswith('TWS')]

            # Merge the DataFrame with the previously created DataFrame based on 'lon' and 'lat'
            df_combined = pd.merge(df_combined, df[['lon', 'lat'] + columns_to_bind], on=['lon', 'lat'], how='outer')
    print(df_combined.head(2))

    length = df_combined.shape[1]
    last_columns = df_combined.columns[3:length]
    df_combined['annual_mean'] = df_combined[last_columns].mean(axis=1)
    df_combined['annual_variance'] = df_combined[last_columns].var(axis=1)
    df_combined['annual_95th_pctl'] = df_combined[last_columns].quantile(0.95, axis=1)
    df_combined['annual_5th_pctl'] = df_combined[last_columns].quantile(0.05, axis=1)

    df_summ = df_combined.iloc[:, :3].join(df_combined.iloc[:, -4:])
    print(df_summ.head(4))
    df_summ.rename(columns={'annual_mean': 'annual_mean'}, inplace=True)
    df_summ.rename(columns={'annual_variance': 'annual_variance'}, inplace=True)
    df_summ.rename(columns={'annual_95th_pctl': 'annual_95th_pctl'}, inplace=True)
    df_summ.rename(columns={'annual_5th_pctl': 'annual_5th_pctl'}, inplace=True)
    df_summ.rename(columns={'Unnamed: 0': 'cell_id'}, inplace=True)
    df_summ['year'] = year
    df_summ.to_csv(f'{year}_summary_TWS.csv', index=False)
    print(f"Made {year} csv")

gldas_20100101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20100101', 'Qle_tavg_20100101',
       'Qh_tavg_20100101', 'Swnet_tavg_20100101', 'Qg_tavg_20100101',
       'Evap_tavg_20100101', 'Qs_tavg_20100101', 'Qsb_tavg_20100101',
       'Qsm_tavg_20100101', 'SnowT_tavg_20100101', 'AvgSurfT_tavg_20100101',
       'SWE_tavg_20100101', 'SnowDepth_tavg_20100101',
       'SoilMoist_S_tavg_20100101', 'SoilMoist_RZ_tavg_20100101',
       'SoilMoist_P_tavg_20100101', 'TVeg_tavg_20100101', 'TWS_tavg_20100101',
       'GWS_tavg_20100101', 'SoilMoist_S_tavg_20100101.1',
       'SoilMoist_RZ_tavg_20100101.1', 'SoilMoist_P_tavg_20100101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20100101
0      515057  64.125  29.375         707.334778
1      516488  61.875  29.625         710.169189
   Unnamed: 0     lon     lat  TWS_tavg_20100101  TWS_tavg_20100102  \
0      536643  60.625  33.125         932.954895         937.467407
1      539523  60.625  33.625        1270.671631        1275.764038

   TWS_tavg_20100103  TWS_tavg_20100104  TWS_tavg_20100105  TWS_tavg_20100106  \
0         938.102173         937.544495         936.968201         936.505676
1        1276.138306        1275.472046        1274.806396        1274.298462

   TWS_tavg_20100107  ...  TWS_tavg_20101222  TWS_tavg_20101223  \
0         936.025940  ...         900.686218         900.682617
1        1273.762695  ...        1233.378174        1233.504761

   TWS_tavg_20101224  TWS_tavg_20101225  TWS_tavg_20101226  TWS_tavg_20101227  \
0         900.675964         900.670227         900.668457         900.667236
1        1233.617920        1233.725952        1233.827271        1233.925049

   TWS_tavg_20101228  TWS_tavg_20101229  TWS_tavg_20101230  TWS_tavg_20101231
0         900.669128         900.665466         900.658569         900.649109
1        1234.023682        1234.114258        1234.174927        1234.231567

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   920.730265       183.933497        937.851868
1      539523  60.625  33.625  1263.400414       359.837918       1285.465332
2      540963  60.625  33.875  1335.406501       391.029916       1358.755054
3      542403  60.625  34.125  1338.488349       338.215053       1359.382544

   annual_5th_pctl
0       900.668591
1      1232.271484
2      1303.333228
3      1308.060669
Made 2010 csv
gldas_20110101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20110101', 'Qle_tavg_20110101',
       'Qh_tavg_20110101', 'Swnet_tavg_20110101', 'Qg_tavg_20110101',
       'Evap_tavg_20110101', 'Qs_tavg_20110101', 'Qsb_tavg_20110101',
       'Qsm_tavg_20110101', 'SnowT_tavg_20110101', 'AvgSurfT_tavg_20110101',
       'SWE_tavg_20110101', 'SnowDepth_tavg_20110101',
       'SoilMoist_S_tavg_20110101', 'SoilMoist_RZ_tavg_20110101',
       'SoilMoist_P_tavg_20110101', 'TVeg_tavg_20110101', 'TWS_tavg_20110101',
       'GWS_tavg_20110101', 'SoilMoist_S_tavg_20110101.1',
       'SoilMoist_RZ_tavg_20110101.1', 'SoilMoist_P_tavg_20110101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20110101
0      515057  64.125  29.375         699.974548
1      516488  61.875  29.625         699.701965
   Unnamed: 0     lon     lat  TWS_tavg_20110101  TWS_tavg_20110102  \
0      536643  60.625  33.125         900.634033         900.625732
1      539523  60.625  33.625        1234.208374        1234.109741

   TWS_tavg_20110103  TWS_tavg_20110104  TWS_tavg_20110105  TWS_tavg_20110106  \
0         900.622437         900.621155         900.619019         900.618958
1        1234.041626        1233.997070        1233.943604        1233.900879

   TWS_tavg_20110107  ...  TWS_tavg_20111222  TWS_tavg_20111223  \
0         900.623779  ...         904.597046         904.457458
1        1233.898926  ...        1234.220215        1234.071777

   TWS_tavg_20111224  TWS_tavg_20111225  TWS_tavg_20111226  TWS_tavg_20111227  \
0         904.306702         904.172607         904.289001         904.224121
1        1233.872681        1233.667480        1234.036987        1233.975708

   TWS_tavg_20111228  TWS_tavg_20111229  TWS_tavg_20111230  TWS_tavg_20111231
0         904.170898         904.100830         904.049194         903.998474
1        1233.941284        1233.906738        1233.915771        1233.937134

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   915.590499       162.733674        940.875403
1      539523  60.625  33.625  1253.013314       316.027053       1284.731592
2      540963  60.625  33.875  1325.026775       310.595451       1358.726318
3      542403  60.625  34.125  1328.674029       274.360279       1359.805566

   annual_5th_pctl
0       901.550989
1      1230.089111
2      1302.032422
3      1307.366821
Made 2011 csv
gldas_20120101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20120101', 'Qle_tavg_20120101',
       'Qh_tavg_20120101', 'Swnet_tavg_20120101', 'Qg_tavg_20120101',
       'Evap_tavg_20120101', 'Qs_tavg_20120101', 'Qsb_tavg_20120101',
       'Qsm_tavg_20120101', 'SnowT_tavg_20120101', 'AvgSurfT_tavg_20120101',
       'SWE_tavg_20120101', 'SnowDepth_tavg_20120101',
       'SoilMoist_S_tavg_20120101', 'SoilMoist_RZ_tavg_20120101',
       'SoilMoist_P_tavg_20120101', 'TVeg_tavg_20120101', 'TWS_tavg_20120101',
       'GWS_tavg_20120101', 'SoilMoist_S_tavg_20120101.1',
       'SoilMoist_RZ_tavg_20120101.1', 'SoilMoist_P_tavg_20120101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20120101
0      515057  64.125  29.375         700.237366
1      516488  61.875  29.625         700.268860
   Unnamed: 0     lon     lat  TWS_tavg_20120101  TWS_tavg_20120102  \
0      536643  60.625  33.125         903.936707         904.229797
1      539523  60.625  33.625        1233.935181        1234.141968

   TWS_tavg_20120103  TWS_tavg_20120104  TWS_tavg_20120105  TWS_tavg_20120106  \
0         904.767517         904.948364         904.962463         904.801636
1        1235.448242        1236.578857        1237.119141        1236.994385

   TWS_tavg_20120107  ...  TWS_tavg_20121222  TWS_tavg_20121223  \
0         904.633057  ...         910.467224         910.468872
1        1236.844604  ...        1226.237305        1225.836060

   TWS_tavg_20121224  TWS_tavg_20121225  TWS_tavg_20121226  TWS_tavg_20121227  \
0         910.053406         909.581238         910.802490         915.810669
1        1225.272705        1224.678711        1225.836426        1230.678711

   TWS_tavg_20121228  TWS_tavg_20121229  TWS_tavg_20121230  TWS_tavg_20121231
0         915.213501         914.575500         914.112183         913.658508
1        1230.037842        1229.339722        1228.772705        1228.247192

[2 rows x 369 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   911.216748        94.618380        929.055573
1      539523  60.625  33.625  1243.503881       274.951513       1268.835022
2      540963  60.625  33.875  1314.666531       296.184075       1341.482300
3      542403  60.625  34.125  1317.852715       248.617372       1339.918213

   annual_5th_pctl
0       900.086731
1      1220.638855
2      1290.755127
3      1295.308777
Made 2012 csv
gldas_20130101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20130101', 'Qle_tavg_20130101',
       'Qh_tavg_20130101', 'Swnet_tavg_20130101', 'Qg_tavg_20130101',
       'Evap_tavg_20130101', 'Qs_tavg_20130101', 'Qsb_tavg_20130101',
       'Qsm_tavg_20130101', 'SnowT_tavg_20130101', 'AvgSurfT_tavg_20130101',
       'SWE_tavg_20130101', 'SnowDepth_tavg_20130101',
       'SoilMoist_S_tavg_20130101', 'SoilMoist_RZ_tavg_20130101',
       'SoilMoist_P_tavg_20130101', 'TVeg_tavg_20130101', 'TWS_tavg_20130101',
       'GWS_tavg_20130101', 'SoilMoist_S_tavg_20130101.1',
       'SoilMoist_RZ_tavg_20130101.1', 'SoilMoist_P_tavg_20130101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20130101
0      515057  64.125  29.375         707.444153
1      516488  61.875  29.625         706.727844
   Unnamed: 0     lon     lat  TWS_tavg_20130101  TWS_tavg_20130102  \
0      536643  60.625  33.125         913.249084         912.848145
1      539523  60.625  33.625        1227.960938        1227.971436

   TWS_tavg_20130103  TWS_tavg_20130104  TWS_tavg_20130105  TWS_tavg_20130106  \
0         912.370605         911.943420         911.538879         911.050293
1        1227.891357        1227.810547        1227.798340        1227.710938

   TWS_tavg_20130107  ...  TWS_tavg_20131222  TWS_tavg_20131223  \
0         911.334717  ...         905.147339         905.027527
1        1227.973877  ...        1205.098877        1204.975708

   TWS_tavg_20131224  TWS_tavg_20131225  TWS_tavg_20131226  TWS_tavg_20131227  \
0         904.920776         904.807251         904.701660         904.613037
1        1204.862305        1204.749268        1204.647705        1204.558838

   TWS_tavg_20131228  TWS_tavg_20131229  TWS_tavg_20131230  TWS_tavg_20131231
0          904.54480         904.461121         904.369873         904.268433
1         1204.50293        1204.423340        1204.334106        1204.240967

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   907.108284        33.152235        916.493652
1      539523  60.625  33.625  1232.416624       177.204300       1248.106494
2      540963  60.625  33.875  1304.168319       200.228822       1321.087769
3      542403  60.625  34.125  1308.441842       181.442237       1323.768921

   annual_5th_pctl
0       900.250903
1      1206.674829
2      1277.044873
3      1280.624756
Made 2013 csv
gldas_20140101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20140101', 'Qle_tavg_20140101',
       'Qh_tavg_20140101', 'Swnet_tavg_20140101', 'Qg_tavg_20140101',
       'Evap_tavg_20140101', 'Qs_tavg_20140101', 'Qsb_tavg_20140101',
       'Qsm_tavg_20140101', 'SnowT_tavg_20140101', 'AvgSurfT_tavg_20140101',
       'SWE_tavg_20140101', 'SnowDepth_tavg_20140101',
       'SoilMoist_S_tavg_20140101', 'SoilMoist_RZ_tavg_20140101',
       'SoilMoist_P_tavg_20140101', 'TVeg_tavg_20140101', 'TWS_tavg_20140101',
       'GWS_tavg_20140101', 'SoilMoist_S_tavg_20140101.1',
       'SoilMoist_RZ_tavg_20140101.1', 'SoilMoist_P_tavg_20140101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20140101
0      515057  64.125  29.375         702.601807
1      516488  61.875  29.625         700.270386
   Unnamed: 0     lon     lat  TWS_tavg_20140101  TWS_tavg_20140102  \
0      536643  60.625  33.125         904.203186         904.877380
1      539523  60.625  33.625        1204.171753        1204.642334

   TWS_tavg_20140103  TWS_tavg_20140104  TWS_tavg_20140105  TWS_tavg_20140106  \
0         904.826477         904.665344         904.537476         904.615784
1        1204.669434        1204.613159        1204.581055        1204.620239

   TWS_tavg_20140107  ...  TWS_tavg_20141222  TWS_tavg_20141223  \
0         907.970825  ...         903.668701         903.537048
1        1206.878052  ...        1206.989258        1206.869019

   TWS_tavg_20141224  TWS_tavg_20141225  TWS_tavg_20141226  TWS_tavg_20141227  \
0         903.632385         903.481750         903.321655         903.173157
1        1208.010620        1207.663818        1207.338867        1207.091309

   TWS_tavg_20141228  TWS_tavg_20141229  TWS_tavg_20141230  TWS_tavg_20141231
0         903.041260         903.049988         903.081177         902.970215
1        1206.883911        1206.923950        1206.873047        1206.683228

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   907.466985        66.570951        928.588147
1      539523  60.625  33.625  1215.710702       126.234222       1238.479395
2      540963  60.625  33.875  1284.152947       286.073010       1316.629028
3      542403  60.625  34.125  1287.774377       186.406305       1312.576123

   annual_5th_pctl
0       899.777795
1      1201.682031
2      1261.768750
3      1269.945239
Made 2014 csv
gldas_20150101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20150101', 'Qle_tavg_20150101',
       'Qh_tavg_20150101', 'Swnet_tavg_20150101', 'Qg_tavg_20150101',
       'Evap_tavg_20150101', 'Qs_tavg_20150101', 'Qsb_tavg_20150101',
       'Qsm_tavg_20150101', 'SnowT_tavg_20150101', 'AvgSurfT_tavg_20150101',
       'SWE_tavg_20150101', 'SnowDepth_tavg_20150101',
       'SoilMoist_S_tavg_20150101', 'SoilMoist_RZ_tavg_20150101',
       'SoilMoist_P_tavg_20150101', 'TVeg_tavg_20150101', 'TWS_tavg_20150101',
       'GWS_tavg_20150101', 'SoilMoist_S_tavg_20150101.1',
       'SoilMoist_RZ_tavg_20150101.1', 'SoilMoist_P_tavg_20150101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20150101
0      515057  64.125  29.375         699.708374
1      516488  61.875  29.625         699.489624
   Unnamed: 0     lon     lat  TWS_tavg_20150101  TWS_tavg_20150102  \
0      536643  60.625  33.125         902.849731         902.736145
1      539523  60.625  33.625        1206.500977        1206.309082

   TWS_tavg_20150103  TWS_tavg_20150104  TWS_tavg_20150105  TWS_tavg_20150106  \
0         903.718567         903.362793         903.068726         902.873718
1        1206.986084        1206.732910        1206.450439        1206.254639

   TWS_tavg_20150107  ...  TWS_tavg_20151222  TWS_tavg_20151223  \
0         902.674500  ...         903.848328         903.638306
1        1206.039062  ...        1211.047729        1210.622437

   TWS_tavg_20151224  TWS_tavg_20151225  TWS_tavg_20151226  TWS_tavg_20151227  \
0         903.453613         903.765564         905.892578         905.652100
1        1210.243286        1210.524780        1213.196167        1212.817383

   TWS_tavg_20151228  TWS_tavg_20151229  TWS_tavg_20151230  TWS_tavg_20151231
0         905.196838         904.788025         904.400391         904.198608
1        1212.404419        1211.997070        1211.522705        1211.306641

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   914.880169       265.846290        952.163635
1      539523  60.625  33.625  1218.954598       240.182011       1250.553955
2      540963  60.625  33.875  1278.029998       260.803901       1308.854443
3      542403  60.625  34.125  1284.231443       156.967646       1308.978418

   annual_5th_pctl
0       899.922058
1      1201.544385
2      1256.614160
3      1268.075317
Made 2015 csv
gldas_20160101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20160101', 'Qle_tavg_20160101',
       'Qh_tavg_20160101', 'Swnet_tavg_20160101', 'Qg_tavg_20160101',
       'Evap_tavg_20160101', 'Qs_tavg_20160101', 'Qsb_tavg_20160101',
       'Qsm_tavg_20160101', 'SnowT_tavg_20160101', 'AvgSurfT_tavg_20160101',
       'SWE_tavg_20160101', 'SnowDepth_tavg_20160101',
       'SoilMoist_S_tavg_20160101', 'SoilMoist_RZ_tavg_20160101',
       'SoilMoist_P_tavg_20160101', 'TVeg_tavg_20160101', 'TWS_tavg_20160101',
       'GWS_tavg_20160101', 'SoilMoist_S_tavg_20160101.1',
       'SoilMoist_RZ_tavg_20160101.1', 'SoilMoist_P_tavg_20160101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20160101
0      515057  64.125  29.375         700.930664
1      516488  61.875  29.625         708.896545
   Unnamed: 0     lon     lat  TWS_tavg_20160101  TWS_tavg_20160102  \
0      536643  60.625  33.125         903.824402         904.953979
1      539523  60.625  33.625        1210.670898        1211.859741

   TWS_tavg_20160103  TWS_tavg_20160104  TWS_tavg_20160105  TWS_tavg_20160106  \
0         910.937256         912.181458         911.578979         911.038757
1        1217.169189        1217.264648        1216.653564        1216.126587

   TWS_tavg_20160107  ...  TWS_tavg_20161222  TWS_tavg_20161223  \
0         910.392273  ...         901.550659         901.518921
1        1215.472046  ...        1203.328369        1203.282104

   TWS_tavg_20161224  TWS_tavg_20161225  TWS_tavg_20161226  TWS_tavg_20161227  \
0         901.502502         901.462585         901.391418         901.335388
1        1203.251465        1203.205200        1203.115356        1203.046143

   TWS_tavg_20161228  TWS_tavg_20161229  TWS_tavg_20161230  TWS_tavg_20161231
0         901.295776         901.261841         901.238525         901.203430
1        1202.996094        1202.945190        1202.917480        1202.875732

[2 rows x 369 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   902.433508         9.271141        909.000076
1      539523  60.625  33.625  1205.480909        16.037405       1214.242462
2      540963  60.625  33.875  1264.922059        38.721391       1275.873260
3      542403  60.625  34.125  1273.348208        22.988457       1282.112366

   annual_5th_pctl
0       899.843231
1      1201.502350
2      1257.786041
3      1267.966431
Made 2016 csv
gldas_20170101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20170101', 'Qle_tavg_20170101',
       'Qh_tavg_20170101', 'Swnet_tavg_20170101', 'Qg_tavg_20170101',
       'Evap_tavg_20170101', 'Qs_tavg_20170101', 'Qsb_tavg_20170101',
       'Qsm_tavg_20170101', 'SnowT_tavg_20170101', 'AvgSurfT_tavg_20170101',
       'SWE_tavg_20170101', 'SnowDepth_tavg_20170101',
       'SoilMoist_S_tavg_20170101', 'SoilMoist_RZ_tavg_20170101',
       'SoilMoist_P_tavg_20170101', 'TVeg_tavg_20170101', 'TWS_tavg_20170101',
       'GWS_tavg_20170101', 'SoilMoist_S_tavg_20170101.1',
       'SoilMoist_RZ_tavg_20170101.1', 'SoilMoist_P_tavg_20170101.1'],
      dtype='object')
   Unnamed: 0     lon     lat  TWS_tavg_20170101
0      515057  64.125  29.375         699.317932
1      516488  61.875  29.625         699.764832
   Unnamed: 0     lon     lat  TWS_tavg_20170101  TWS_tavg_20170102  \
0      536643  60.625  33.125         901.177002         901.536438
1      539523  60.625  33.625        1202.844360        1203.553467

   TWS_tavg_20170103  TWS_tavg_20170104  TWS_tavg_20170105  TWS_tavg_20170106  \
0         902.014282         902.152283         902.178040         902.092102
1        1204.821045        1204.730591        1204.465088        1204.214844

   TWS_tavg_20170107  ...  TWS_tavg_20171222  TWS_tavg_20171223  \
0         901.995728  ...         901.265442         901.270081
1        1204.026978  ...        1213.824341        1213.806152

   TWS_tavg_20171224  TWS_tavg_20171225  TWS_tavg_20171226  TWS_tavg_20171227  \
0         901.267212         901.249939         901.246704         901.281555
1        1213.775391        1213.711792        1213.693970        1213.742798

   TWS_tavg_20171228  TWS_tavg_20171229  TWS_tavg_20171230  TWS_tavg_20171231
0         901.260193         901.230957         901.200256         901.174316
1        1213.692017        1213.629272        1213.567505        1213.513794

[2 rows x 368 columns]
   Unnamed: 0     lon     lat  annual_mean  annual_variance  annual_95th_pctl  \
0      536643  60.625  33.125   909.762253       174.377226        935.912158
1      539523  60.625  33.625  1222.647870       125.725064       1244.709131
2      540963  60.625  33.875  1286.435335       125.064423       1309.496338
3      542403  60.625  34.125  1292.997320       113.324793       1315.430151

   annual_5th_pctl
0       900.497803
1      1209.320605
2      1265.862256
3      1276.556494
Made 2017 csv
gldas_20180101.csv
Index(['Unnamed: 0', 'lon', 'lat', 'Lwnet_tavg_20180101', 'Qle_tavg_20180101',
       'Qh_tavg_20180101', 'Swnet_tavg_20180101', 'Qg_tavg_20180101',
       'Evap_tavg_20180101', 'Qs_tavg_20180101', 'Qsb_tavg_20180101',
       'Qsm_tavg_20180101', 'SnowT_tavg_20180101', 'AvgSurfT_tavg_20180101',